apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzamypage
  labels:
    app: pizzamypage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzamypage
  template:
    metadata:
      labels:
        app: pizzamypage
    spec:
      containers:
        - name: pizzamypage
          image: username/pizzamypage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5